### ISSUE TITLE
Technology Radar page not working

### ISSUE THREAD

**Issue by kdsch** [embeddedartistry/embeddedartistry.github.io#1]
When I visit the Technology Radar page, it doesn't display the radar. I think the reason is that the encoding of the URL isn't right. The URL of the page is this:

```
https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fembeddedartistry%2Fembeddedartistry.github.io%2Fmaster%2Ftechnology-radar%2FEmbedded%2520Artistry%2520Technology%2520Radar.csv
```

which decodes to

```
https://radar.thoughtworks.com/?sheetId=https://raw.githubusercontent.com/embeddedartistry/embeddedartistry.github.io/master/technology-radar/Embedded%20Artistry%20Technology%20Radar.csv
```

**Comment by phillipjohnston** [comment]
The problem is actually that Thoughtworks changed the URL parameter from `sheetId` to `documentId`.  Not the first time the URL requirements have changed...

**Comment by phillipjohnston** [comment]
The links in the website menu and the relevant article are updated now, though caching may prevent you from seeing that for a few hours. Let me know if there's another link you used that I missed.

Here's the proper link: https://radar.thoughtworks.com/?documentId=https%3A%2F%2Fraw.githubusercontent.com%2Fembeddedartistry%2Fembeddedartistry.github.io%2Fmaster%2Ftechnology-radar%2FEmbedded%2520Artistry%2520Technology%2520Radar.csv
